#swaggerIOT.yaml
openapi: 3.0.0
info:
  title: Datos Sensores API
  description: API para la gestión de datos de sensores.
  version: 1.0.0

servers:
  - url: https://3.145.63.126/sensores/
    description: Servidor local

paths:
  /:
    get:
      summary: Obtener todos los registros de sensores
      responses:
        '200':
          description: Lista de registros de sensores
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nivel_temperatura1:
                      type: number
                      format: float
                    estado_ventilador1:
                      type: string
                      enum:
                        - Encendido
                        - Apagado
                    nivel_temperatura2:
                      type: number
                      format: float
                    estado_ventilador2:
                      type: string
                      enum:
                        - Encendido
                        - Apagado
                    luz:
                      type: string
                      enum:
                        - Encendida
                        - Apagada
                    estado_led:
                      type: string
                      enum:
                        - Encendido
                        - Apagado
                    agua_detectada:
                      type: boolean
                    posicion_servo:
                      type: number
                      format: float
                    humedad_suelo1:
                      type: number
                      format: float
                    estado_bomba1:
                      type: string
                      enum:
                        - Encendida
                        - Apagada
                    estado_bomba2:
                      type: string
                      enum:
                        - Encendida
                        - Apagada
                    distancia1:
                      type: number
                      format: float
                    humedad_suelo2:
                      type: number
                      format: float
                    estado_bomba3:
                      type: string
                      enum:
                        - Encendida
                        - Apagada
                    estado_bomba4:
                      type: string
                      enum:
                        - Encendida
                        - Apagada
                    distancia2:
                      type: number
                      format: float
              examples:
                application/json:
                  value:
                    - id: 1
                      nivel_temperatura1: 22.5
                      estado_ventilador1: Encendido
                      nivel_temperatura2: 20.3
                      estado_ventilador2: Apagado
                      luz: Encendida
                      estado_led: Apagado
                      agua_detectada: true
                      posicion_servo: 45.0
                      humedad_suelo1: 80.5
                      estado_bomba1: Apagada
                      estado_bomba2: Encendida
                      distancia1: 10.5
                      humedad_suelo2: 70.0
                      estado_bomba3: Apagada
                      estado_bomba4: Apagada
                      distancia2: 12.0
        '500':
          description: Error en el servidor
    post:
      summary: Crear un nuevo registro de sensor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nivel_temperatura1:
                  type: number
                  format: float
                estado_ventilador1:
                  type: string
                  enum:
                    - Encendido
                    - Apagado
                nivel_temperatura2:
                  type: number
                  format: float
                estado_ventilador2:
                  type: string
                  enum:
                    - Encendido
                    - Apagado
                luz:
                  type: string
                  enum:
                    - Encendida
                    - Apagada
                estado_led:
                  type: string
                  enum:
                    - Encendido
                    - Apagado
                agua_detectada:
                  type: boolean
                posicion_servo:
                  type: number
                  format: float
                humedad_suelo1:
                  type: number
                  format: float
                estado_bomba1:
                  type: string
                  enum:
                    - Encendida
                    - Apagada
                estado_bomba2:
                  type: string
                  enum:
                    - Encendida
                    - Apagada
                distancia1:
                  type: number
                  format: float
                humedad_suelo2:
                  type: number
                  format: float
                estado_bomba3:
                  type: string
                  enum:
                    - Encendida
                    - Apagada
                estado_bomba4:
                  type: string
                  enum:
                    - Encendida
                    - Apagada
                distancia2:
                  type: number
                  format: float
      responses:
        '201':
          description: Registro de sensor creado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nivel_temperatura1:
                    type: number
                    format: float
                  estado_ventilador1:
                    type: string
                  nivel_temperatura2:
                    type: number
                    format: float
                  estado_ventilador2:
                    type: string
                  luz:
                    type: string
                  estado_led:
                    type: string
                  agua_detectada:
                    type: boolean
                  posicion_servo:
                    type: number
                    format: float
                  humedad_suelo1:
                    type: number
                    format: float
                  estado_bomba1:
                    type: string
                  estado_bomba2:
                    type: string
                  distancia1:
                    type: number
                    format: float
                  humedad_suelo2:
                    type: number
                    format: float
                  estado_bomba3:
                    type: string
                  estado_bomba4:
                    type: string
                  distancia2:
                    type: number
                    format: float
              examples:
                application/json:
                  value:
                    id: 1
                    nivel_temperatura1: 22.5
                    estado_ventilador1: Encendido
                    nivel_temperatura2: 20.3
                    estado_ventilador2: Apagado
                    luz: Encendida
                    estado_led: Apagado
                    agua_detectada: true
                    posicion_servo: 45.0
                    humedad_suelo1: 80.5
                    estado_bomba1: Apagada
                    estado_bomba2: Encendida
                    distancia1: 10.5
                    humedad_suelo2: 70.0
                    estado_bomba3: Apagada
                    estado_bomba4: Apagada
                    distancia2: 12.0
        '400':
          description: Error en los datos proporcionados
        '500':
          description: Error en el servidor

  /{dato_id}:
    get:
      summary: Obtener un registro de sensor por ID
      parameters:
        - name: dato_id
          in: path
          required: true
          description: ID del registro de sensor
          schema:
            type: integer
      responses:
        '200':
          description: Información del registro de sensor
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nivel_temperatura1:
                    type: number
                    format: float
                  estado_ventilador1:
                    type: string
                  nivel_temperatura2:
                    type: number
                    format: float
                  estado_ventilador2:
                    type: string
                  luz:
                    type: string
                  estado_led:
                    type: string
                  agua_detectada:
                    type: boolean
                  posicion_servo:
                    type: number
                    format: float
                  humedad_suelo1:
                    type: number
                    format: float
                  estado_bomba1:
                    type: string
                  estado_bomba2:
                    type: string
                  distancia1:
                    type: number
                    format: float
                  humedad_suelo2:
                    type: number
                    format: float
                  estado_bomba3:
                    type: string
                  estado_bomba4:
                    type: string
                  distancia2:
                    type: number
                    format: float
              examples:
                application/json:
                  value:
                    id: 1
                    nivel_temperatura1: 22.5
                    estado_ventilador1: Encendido
                    nivel_temperatura2: 20.3
                    estado_ventilador2: Apagado
                    luz: Encendida
                    estado_led: Apagado
                    agua_detectada: true
                    posicion_servo: 45.0
                    humedad_suelo1: 80.5
                    estado_bomba1: Apagada
                    estado_bomba2: Encendida
                    distancia1: 10.5
                    humedad_suelo2: 70.0
                    estado_bomba3: Apagada
                    estado_bomba4: Apagada
                    distancia2: 12.0
        '404':
          description: Registro de sensor no encontrado
        '500':
          description: Error en el servidor

    delete:
      summary: Eliminar un registro de sensor por ID
      parameters:
        - name: dato_id
          in: path
          required: true
          description: ID del registro de sensor
          schema:
            type: integer
      responses:
        '200':
          description: Registro de sensor eliminado
        '404':
          description: Registro de sensor no encontrado
        '500':
          description: Error en el servidor
