openapi: 3.0.0
info:
  title: User API
  description: API para la gestión de usuarios.
  version: 1.0.0

servers:
  - url: https://3.145.63.126/users/
    description: Servidor local

paths:
  /:
    get:
      summary: Obtener todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nombre:
                      type: string
                    correo:
                      type: string
                    rol:
                      type: string
                      enum:
                        - Administrador
                        - Usuario
                    fecha_nacimiento:
                      type: string
                      format: date
                    sexo:
                      type: string
                      enum:
                        - Femenino
                        - Masculino
                    foto:
                      type: string
                      format: uri
                      nullable: true  # Hacemos explícito que puede ser null
              examples:
                application/json:
                  value: 
                    - id: 1
                      nombre: Juan Pérez
                      correo: juan.perez@example.com
                      rol: Usuario
                      fecha_nacimiento: 1990-01-01
                      sexo: Masculino
                      foto: http://example.com/foto.jpg
                    - id: 2
                      nombre: María García
                      correo: maria.garcia@example.com
                      rol: Administrador
                      fecha_nacimiento: 1985-05-15
                      sexo: Femenino
                      foto: http://example.com/foto2.jpg
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error en el servidor
    post:
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                correo:
                  type: string
                password:
                  type: string
                rol:
                  type: string
                  enum:
                    - Administrador
                    - Usuario
                fecha_nacimiento:
                  type: string
                  format: date
                sexo:
                  type: string
                  enum:
                    - Femenino
                    - Masculino
                foto:
                  type: string
                  format: binary
                  nullable: true  # Hacemos explícito que puede ser null
      responses:
        '201':
          description: Usuario creado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre:
                    type: string
                  correo:
                    type: string
                  rol:
                    type: string
                    enum:
                      - Administrador
                      - Usuario
                  fecha_nacimiento:
                    type: string
                    format: date
                  sexo:
                    type: string
                    enum:
                      - Femenino
                      - Masculino
                  foto:
                    type: string
                    format: uri
                    nullable: true  # Hacemos explícito que puede ser null
              examples:
                application/json:
                  value:
                    id: 3
                    nombre: Pedro López
                    correo: pedro.lopez@example.com
                    rol: Usuario
                    fecha_nacimiento: 1992-03-25
                    sexo: Masculino
                    foto: null  # Enviamos foto como null
        '400':
          description: Error en los datos proporcionados
        '500':
          description: Error en el servidor

  /{user_id}:
    get:
      summary: Obtener un usuario por ID
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID del usuario
          schema:
            type: integer
      responses:
        '200':
          description: Información del usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre:
                    type: string
                  correo:
                    type: string
                  rol:
                    type: string
                    enum:
                      - Administrador
                      - Usuario
                  fecha_nacimiento:
                    type: string
                    format: date
                  sexo:
                    type: string
                    enum:
                      - Femenino
                      - Masculino
                  foto:
                    type: string
                    format: uri
                    nullable: true  # Hacemos explícito que puede ser null
              examples:
                application/json:
                  value:
                    id: 1
                    nombre: Juan Pérez
                    correo: juan.perez@example.com
                    rol: Usuario
                    fecha_nacimiento: 1990-01-01
                    sexo: Masculino
                    foto: http://example.com/foto.jpg
        '404':
          description: Usuario no encontrado
        '500':
          description: Error en el servidor

    put:
      summary: Actualizar un usuario por ID
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID del usuario
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                correo:
                  type: string
                password:
                  type: string
                rol:
                  type: string
                  enum:
                    - Administrador
                    - Usuario
                fecha_nacimiento:
                  type: string
                  format: date
                sexo:
                  type: string
                  enum:
                    - Femenino
                    - Masculino
      responses:
        '200':
          description: Usuario actualizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre:
                    type: string
                  correo:
                    type: string
                  rol:
                    type: string
                    enum:
                      - Administrador
                      - Usuario
                  fecha_nacimiento:
                    type: string
                    format: date
                  sexo:
                    type: string
                    enum:
                      - Femenino
                      - Masculino
              examples:
                application/json:
                  value:
                    id: 1
                    nombre: Juan Pérez Actualizado
                    correo: juan.perez.updated@example.com
                    rol: Administrador
                    fecha_nacimiento: 1990-01-01
                    sexo: Masculino
        '400':
          description: Error en los datos proporcionados
        '404':
          description: Usuario no encontrado
        '500':
          description: Error en el servidor

    delete:
      summary: Eliminar un usuario por ID
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID del usuario
          schema:
            type: integer
      responses:
        '200':
          description: Usuario eliminado
        '404':
          description: Usuario no encontrado
        '500':
          description: Error en el servidor

  /check-email:
    post:
      summary: Verificar si un correo está registrado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correo:
                  type: string
      responses:
        '200':
          description: Resultado de la verificación del correo
          content:
            application/json:
              schema:
                type: object
                properties:
                  exists:
                    type: boolean
              examples:
                application/json:
                  value:
                    exists: true
        '400':
          description: El campo correo es obligatorio
        '500':
          description: Error en el servidor

  /login:
    post:
      summary: Iniciar sesión con correo y contraseña
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correo:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Respuesta de inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
              examples:
                application/json:
                  value:
                    token: "abc123tokenxyz"
        '400':
          description: Error de autenticación
        '500':
          description: Error en el servidor
