openapi: 3.0.0
info:
  title: User API
  description: API para la gestión de usuarios.
  version: 1.0.0

servers:
  - url: https://3.145.63.126/users/
    description: Servidor local

paths:
  /:
    get:
      summary: Obtener todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nombre:
                      type: string
                    correo:
                      type: string
                    rol:
                      type: string
                    fecha_nacimiento:
                      type: string
                      format: date
                    sexo:
                      type: string
                    foto:
                      type: string
                      format: uri
    post:
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                correo:
                  type: string
                password:
                  type: string
                rol:
                  type: string
                fecha_nacimiento:
                  type: string
                  format: date
                sexo:
                  type: string
                foto:
                  type: string
                  format: binary
      responses:
        '201':
          description: Usuario creado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre:
                    type: string
                  correo:
                    type: string
                  rol:
                    type: string
                  fecha_nacimiento:
                    type: string
                    format: date
                  sexo:
                    type: string
                  foto:
                    type: string
                    format: uri
        '400':
          description: Error en los datos proporcionados

  /{user_id}:
    get:
      summary: Obtener un usuario por ID
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID del usuario
          schema:
            type: integer
      responses:
        '200':
          description: Información del usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre:
                    type: string
                  correo:
                    type: string
                  rol:
                    type: string
                  fecha_nacimiento:
                    type: string
                    format: date
                  sexo:
                    type: string
                  foto:
                    type: string
                    format: uri
        '404':
          description: Usuario no encontrado

    put:
      summary: Actualizar un usuario por ID
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID del usuario
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                correo:
                  type: string
                password:
                  type: string
                rol:
                  type: string
                fecha_nacimiento:
                  type: string
                  format: date
                sexo:
                  type: string
      responses:
        '200':
          description: Usuario actualizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre:
                    type: string
                  correo:
                    type: string
                  rol:
                    type: string
                  fecha_nacimiento:
                    type: string
                    format: date
                  sexo:
                    type: string
        '400':
          description: Error en los datos proporcionados
        '404':
          description: Usuario no encontrado

    delete:
      summary: Eliminar un usuario por ID
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID del usuario
          schema:
            type: integer
      responses:
        '200':
          description: Usuario eliminado
        '404':
          description: Usuario no encontrado

  /check-email:
    post:
      summary: Verificar si un correo está registrado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correo:
                  type: string
      responses:
        '200':
          description: Resultado de la verificación del correo
          content:
            application/json:
              schema:
                type: object
                properties:
                  exists:
                    type: boolean
        '400':
          description: El campo correo es obligatorio

  /login:
    post:
      summary: Iniciar sesión con correo y contraseña
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correo:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Respuesta de inicio de sesión exitoso
        '400':
          description: Error de autenticación
