openapi: 3.0.0
info:
  title: User API
  description: API para la gestión de usuarios.
  version: 1.0.0

servers:
  - url: https://3.145.63.126/users/
    description: Servidor local

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
          example: "Error desconocido"
          
    AuthResponse:
      type: object
      properties:
        token:
          type: string
        user:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
              example: "Juan Pérez"
            email:
              type: string
              example: "juan@example.com"

paths:
  /:
    get:
      summary: Obtener todos los usuarios
      operationId: getUsers
      responses:
        '200':
          description: Lista de usuarios obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                      example: "Juan Pérez"
                    email:
                      type: string
                      example: "juan@example.com"
        '400':
          description: Solicitud incorrecta. Verifique los parámetros enviados.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                badRequest:
                  value:
                    error: "Bad Request"
                    message: "Los parámetros enviados son incorrectos."
        '500':
          description: Error interno del servidor. Inténtelo más tarde.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                internalError:
                  value:
                    error: "Internal Server Error"
                    message: "Hubo un error en el servidor. Inténtelo de nuevo más tarde."

    post:
      summary: Crear un nuevo usuario
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Juan Pérez"
                email:
                  type: string
                  example: "juan@example.com"
                password:
                  type: string
                  example: "password123"
              required:
                - name
                - email
                - password
      responses:
        '201':
          description: Usuario creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                    example: "Juan Pérez"
                  email:
                    type: string
                    example: "juan@example.com"
        '400':
          description: Datos inválidos. Verifique que los campos sean correctos y completos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalidData:
                  value:
                    error: "Invalid Data"
                    message: "Verifique que todos los campos sean correctos."
        '500':
          description: Error interno del servidor. Inténtelo más tarde.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                internalError:
                  value:
                    error: "Internal Server Error"
                    message: "Hubo un error en el servidor. Inténtelo de nuevo más tarde."

  /{user_id}:
    get:
      summary: Obtener un usuario por ID
      operationId: getUserById
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Datos del usuario obtenidos correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                    example: "Juan Pérez"
                  email:
                    type: string
                    example: "juan@example.com"
        '400':
          description: ID de usuario inválido. Debe ser un número entero.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalidUserId:
                  value:
                    error: "Invalid User ID"
                    message: "El ID del usuario debe ser un número entero."
        '404':
          description: Usuario no encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                userNotFound:
                  value:
                    error: "User Not Found"
                    message: "No se encontró un usuario con el ID especificado."
        '500':
          description: Error interno del servidor. Inténtelo más tarde.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                internalError:
                  value:
                    error: "Internal Server Error"
                    message: "Hubo un error en el servidor. Inténtelo de nuevo más tarde."

    put:
      summary: Actualizar un usuario por ID
      operationId: updateUser
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Juan Pérez"
                email:
                  type: string
                  example: "juan@example.com"
      responses:
        '200':
          description: Usuario actualizado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                    example: "Juan Pérez"
                  email:
                    type: string
                    example: "juan@example.com"
        '400':
          description: Datos inválidos. Verifique que los campos sean correctos y completos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalidData:
                  value:
                    error: "Invalid Data"
                    message: "Verifique que todos los campos sean correctos."
        '404':
          description: Usuario no encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                userNotFound:
                  value:
                    error: "User Not Found"
                    message: "No se encontró un usuario con el ID especificado."
        '500':
          description: Error interno del servidor. Inténtelo más tarde.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                internalError:
                  value:
                    error: "Internal Server Error"
                    message: "Hubo un error en el servidor. Inténtelo de nuevo más tarde."

    delete:
      summary: Eliminar un usuario por ID
      operationId: deleteUser
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Usuario eliminado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Usuario eliminado correctamente"
        '400':
          description: ID de usuario inválido. Debe ser un número entero.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalidUserId:
                  value:
                    error: "Invalid User ID"
                    message: "El ID del usuario debe ser un número entero."
        '404':
          description: Usuario no encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                userNotFound:
                  value:
                    error: "User Not Found"
                    message: "No se encontró un usuario con el ID especificado."
        '500':
          description: Error interno del servidor. Inténtelo más tarde.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                internalError:
                  value:
                    error: "Internal Server Error"
                    message: "Hubo un error en el servidor. Inténtelo de nuevo más tarde."

  /login:
    post:
      summary: Iniciar sesión de usuario
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "juan@example.com"
                password:
                  type: string
                  example: "password123"
              required:
                - email
                - password
      responses:
        '200':
          description: Inicio de sesión exitoso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Datos inválidos. Verifique las credenciales proporcionadas.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalidCredentials:
                  value:
                    error: "Invalid Credentials"
                    message: "Las credenciales proporcionadas no son válidas."
        '401':
          description: Credenciales incorrectas.
         
